### ISSUE TITLE
shoulder-core 单测在非spring环境运行失败

### ISSUE THREAD

**Issue by alex-pro-plus** [ChinaLym/shoulder-framework#18]
# BUG 影响
使用者无影响，主要表现为单测不通过。

## BUG 相关模块以及功能
**`shoulder-core` 的锁**
`LockInfo`类有多个构造函数，其中有一个简化的构造函数，部分属性有默认值，设置这部分默认值时选择从上下文获取，获取不到会报错。
### 功能设计背景
> 为何提供了该构造函数：依赖 spring 上下文读取配置以获取instanceId，便于自适应集群环境，保持在集群时开发者代码不需要动就能使用。

# BUG 代码
![image](https://github.com/ChinaLym/shoulder-framework/assets/168884289/90ff9ac9-d7d0-40d0-bf79-b52f8f8ca517)

# 建议的解决方案
修改代码，修复单测，使用全部参数构造函数，同时开发全部参数构造函数给使用者。

**Comment by ChinaLym** [comment]
已收到~感谢来信！

**Comment by ChinaLym** [comment]
see in [releases 0.8.1](https://github.com/ChinaLym/shoulder-framework/releases)
